# Generated by Django 4.1.4 on 2023-01-19 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_user_email_verified_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_verification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
