# Generated by Django 4.1.4 on 2022-12-08 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clinic',
            new_name='Clinics',
        ),
    ]
