# Generated by Django 4.1.4 on 2022-12-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0003_alter_clinics_clinic_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinics',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
