# Generated by Django 4.1.4 on 2023-01-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0006_clinics_created_at_clinics_updated_at_clinics_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinics',
            name='clinic_fb',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
