# Generated by Django 4.1.4 on 2023-01-17 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0007_clinics_clinic_fb'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinics',
            name='clinic_hours',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
