# Generated by Django 4.1.4 on 2022-12-08 13:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseases',
            name='test',
            field=models.TextField(default=django.utils.timezone.now, max_length=999),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diseases',
            name='causes',
            field=models.TextField(max_length=999),
        ),
        migrations.AlterField(
            model_name='diseases',
            name='overview',
            field=models.TextField(max_length=999),
        ),
        migrations.AlterField(
            model_name='diseases',
            name='prevention',
            field=models.TextField(max_length=999),
        ),
        migrations.AlterField(
            model_name='diseases',
            name='symptoms',
            field=models.TextField(max_length=999),
        ),
        migrations.AlterField(
            model_name='diseases',
            name='treatment',
            field=models.TextField(max_length=999),
        ),
    ]
